spring:
    datasource:
        url: jdbc:mysql://121.196.101.64:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: 781003
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8084
#指定xml文件所在的位置,扫描并生成代理类,由主类上的注解@MapperScan("net.seehope.**.mapper")实现
mybatis:
    mapper-locations:
 #       - classpath*:mapper/**/*.xml
        - classpath*:com/lifeng/shopserver/mapper/xml/*.xml
